name: Bug report
description: File a bug report to help us improve SUP
labels: [bug]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please include as much detail as possible.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened, and what did you expect?
      placeholder: Clear, concise description of the bug
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Reproduction steps / minimal program
      description: Provide a minimal `.sup` program or steps to reproduce
      render: text
  - type: input
    id: version
    attributes:
      label: Version
      placeholder: e.g., sup-lang 0.2.3
  - type: textarea
    id: env
    attributes:
      label: Environment
      description: OS, Python version, CLI command used
      render: text
  - type: textarea
    id: logs
    attributes:
      label: Logs / screenshots
      description: Paste any relevant error output or screenshots
      render: text

