name: Feature request
description: Suggest an idea for this project
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your suggestion!
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: Is your feature request related to a problem? Please describe.
    validations:
      required: false
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: Describe the solution you'd like
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
    validations:
      required: false
name: Feature request
description: Suggest an idea for SUP
labels: [enhancement]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping make SUP better! Tell us about the problem your feature would solve.
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: Is your feature request related to a problem?
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: Describe the feature you'd like
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
  - type: textarea
    id: additional
    attributes:
      label: Additional context

