name: Docs

on:
  push:
    branches: [ main ]
    paths:
      - 'sup-lang/docs/**'
      - 'sup-lang/mkdocs.yml'
      - '.github/workflows/docs.yml'

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Build docs
        working-directory: sup-lang
        run: |
          python -m pip install -U pip mkdocs
          mkdocs build --strict
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: sup-lang/site

