site_name: SUP Language
nav:
  - Home: index.md
  - Language Spec: spec.md
  - Quickstart: quickstart.md
  - Standard Library: stdlib.md
  - Modules: modules.md
  - Types: types.md
  - Versioning: versioning.md
  - Packaging: packaging.md
theme:
  name: readthedocs

