name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.10', '3.11', '3.12', '3.13']

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install project and tooling
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e sup-lang
          python -m pip install pre-commit pytest pytest-cov hypothesis

      - name: Run pre-commit
        run: pre-commit run -a

      - name: Run tests with coverage
        run: pytest -q sup-lang --cov=sup --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage.xml
          flags: unittests
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Run performance gates
        if: ${{ matrix.os == 'ubuntu-latest' && matrix.python-version == '3.12' }}
        run: |
          python -m pip install -e sup-lang
          python -m sup.tools.bench_gates

      - name: Run memory probe (non-blocking)
        if: ${{ matrix.os == 'ubuntu-latest' && matrix.python-version == '3.12' }}
        run: |
          set +e
          python -m sup.tools.mem_probe || true

