name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    name: Tests (Python ${{ matrix.python }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python: ["3.11"]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest pytest-cov ruff mypy
          python -m pip install -e ./sup-lang

      - name: Lint (ruff)
        run: |
          ruff check sup-lang/sup || true

      - name: Type check (mypy)
        run: |
          mypy sup-lang/sup || true

      - name: Run tests
        run: |
          pytest -q --maxfail=1 --disable-warnings --cov=sup-lang/sup --cov-report=term-missing sup-lang

  conformance:
    name: Conformance (spec suite)
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install
        run: |
          python -m pip install -U pip
          python -m pip install -e ./sup-lang pytest
      - name: Run conformance tests
        run: |
          pytest -q sup-lang

  perf:
    name: Perf benchmarks
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install
        run: |
          python -m pip install -U pip
          python -m pip install -e ./sup-lang
          python -c "import sup, sys; print('sup import ok', sup.__version__)"
      - name: Run benchmarks
        run: |
          python sup-lang/sup/tools/benchmarks.py --case arith_loop --iters 5 --json --out perf.json
      - name: Enforce performance budgets
        run: |
          python sup-lang/sup/tools/bench_gates.py
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: perf.json
          path: perf.json


