name: Docs

on:
  push:
    branches: [ main, master ]
    paths:
      - 'sup-lang/docs/**'
      - 'sup-lang/mkdocs.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install mkdocs
        run: |
          python -m pip install --upgrade pip
          python -m pip install mkdocs mkdocs-material mkdocs-minify-plugin mkdocs-git-revision-date-localized-plugin

      - name: Build and deploy
        working-directory: sup-lang
        run: |
          mkdocs gh-deploy --force


