name: ClusterFuzzLite

on:
  pull_request:
    branches: [ main, master ]
  push:
    branches: [ main, master ]
  schedule:
    - cron: '0 4 * * *'

permissions:
  contents: read

jobs:
  fuzz:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        working-directory: sup-lang
        run: |
          python -m pip install --upgrade pip
          pip install . pytest hypothesis atheris
      - name: Run fuzzers (parser)
        working-directory: sup-lang
        run: |
          python - << 'PY'
import atheris, sys
with atheris.instrument_imports():
    from sup.parser import Parser

def TestOneInput(data: bytes):
    try:
        s = data.decode('utf-8', errors='ignore')
        Parser().parse(s)
    except Exception:
        pass

atheris.Setup(sys.argv, TestOneInput)
atheris.Fuzz()
PY


