name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Build package
        run: |
          python -m pip install --upgrade pip build
          cd sup-lang
          python -m build
          cd ..

      - name: Generate SBOM (CycloneDX)
        run: |
          python -m pip install cyclonedx-bom
          cyclonedx-py --evidence -r -o sbom.json

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: |
            sup-lang/dist/*
            sbom.json

      - name: Publish to PyPI
        if: startsWith(github.ref, 'refs/tags/v')
        uses: pypa/gh-action-pypi-publish@v1.12.2
        with:
          packages-dir: sup-lang/dist
          skip-existing: true
          print-hash: true


