name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  pypi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Build package
        working-directory: sup-lang
        run: |
          python -m pip install -U pip build
          python -m build
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages-dir: sup-lang/dist
          skip-existing: true

  vsix:
    runs-on: ubuntu-latest
    needs: pypi
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Package VS Code extension
        working-directory: sup-lang/vscode-extension
        run: |
          npm i -g @vscode/vsce
          vsce package
      - name: Upload VSIX to release
        uses: softprops/action-gh-release@v2
        with:
          files: sup-lang/vscode-extension/*.vsix
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

