name: Scorecard supply-chain analysis

on:
  schedule:
    - cron: '0 2 * * 1'
  push:
    branches: [ main, master ]

permissions:
  security-events: write
  id-token: write
  contents: read

jobs:
  analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: ossf/scorecard-action@v2.3.3
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true
      - uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif


